--산술연산자

SELECT ENAME , SAL, sal * 1.1 
FROM T_EMP ;

SELECT ENAME , SAL , COMM, sal + COMM -- null 값과의 산술연산은 무 조 건 NULL!
FROM T_EMP ;

-- WHERE 조건절
SELECT *
FROM T_EMP
WHERE job='SALESMAN'; -- 문자열은 대소문자 구분!

--p13
SELECT ename, sal, deptno
FROM T_EMP 
WHERE deptno = 10;

SELECT ename, SAL 
FROM T_EMP 
WHERE sal > 2000;

SELECT ENAME , EMPNO , SAL 
FROM T_EMP 
WHERE ENAME ='SCOTT';

SELECT ENAME , JOB 
FROM T_EMP 
WHERE job IN ('CLERK', 'ANALYST');

SELECT NAME , GRADE 
FROM T_STUDENT 
WHERE GRADE = 2 OR grade= 3;

SELECT NAME , GRADE 
FROM T_STUDENT 
WHERE GRADE IN (2, 3);

SELECT NAME , GRADE 
FROM T_STUDENT 
WHERE GRADE >1 AND grade <4 ;

SELECT NAME , GRADE 
FROM T_STUDENT 
WHERE GRADE = 2 OR grade= 3;

SELECT NAME , GRADE 
FROM T_STUDENT 
WHERE GRADE NOT IN (1, 4);

SELECT NAME , GRADE 
FROM T_STUDENT 
WHERE GRADE BETWEEN 2 AND 3;

SELECT name, PAY , POSITION
FROM T_PROFESSOR 
WHERE pay > 300;

SELECT name, POSITION
FROM T_PROFESSOR 
WHERE BONUS IS NULL;

-- LIKE
SELECT NAME 
FROM T_PROFESSOR WHERE NAME LIKE '김%'; 

SELECT ename
FROM T_EMP WHERE ENAME  LIKE '%NE%';

SELECT ENAME 
FROM T_EMP WHERE ENAME LIKE '_A%';

--ORDER BY
SELECT ENAME 
FROM T_EMP WHERE ENAME LIKE '%L%'  
ORDER BY ENAME DESC ;

SELECT ENAME , JOB , SAL 
FROM T_EMP ORDER BY job DESC, SAL ASC  ;

SELECT name, GRADE , HEIGHT 
FROM T_STUDENT ORDER BY grade ASC, HEIGHT DESC ;