--#7201
SELECT GRADE, max(HEIGHT ) 
FROM T_STUDENT 
GROUP BY GRADE 
;

SELECT grade "학년" , NAME , HEIGHT 
FROM T_STUDENT 
WHERE (GRADE , HEIGHT ) IN (SELECT GRADE, max(HEIGHT ) FROM T_STUDENT GROUP BY GRADE )
--ORDER BY GRADE ASC 
--ORDER BY 1
ORDER BY "학년" -- ORDER BY만 유일하게 별명을 사용할 수 있다. 마지막에 수행되므로!
;

--#7202
SELECT min(HIREDATE )FROM T_PROFESSOR GROUP BY DEPTNO ;


SELECT p.PROFNO , p.NAME , p.HIREDATE ,d.DNAME 
FROM T_PROFESSOR p, T_DEPARTMENT d
WHERE p.DEPTNO = d.DEPTNO AND p.HIREDATE  IN (SELECT min(HIREDATE )FROM T_PROFESSOR GROUP BY DEPTNO)
ORDER BY d.DNAME ASC 
;

--#7203
SELECT POST , MAX(PAY) 
FROM T_EMP2 
GROUP BY POST 
;

SELECT NAME , POST , PAY 
FROM T_EMP2 
WHERE (post, PAY ) in (SELECT POST , MAX(PAY) FROM T_EMP2 GROUP BY POST)
ORDER BY pay ASC 
;

--#7204
SELECT AVG(PAY)FROM T_EMP2 GROUP BY DEPTNO ;

SELECT d.DNAME , e.NAME , e.PAY 
FROM T_EMP2 e , T_DEPT2 d
WHERE e.DEPTNO = d.DCODE AND e.PAY <all (SELECT AVG(PAY)FROM T_EMP2 GROUP BY DEPTNO)
ORDER BY e.PAY 
;

--#7205
SELECT a.NAME "사원이름", nvl(a.POST, ' ') "직급", a.PAY "급여"
FROM T_EMP2 a
WHERE a.PAY >= (SELECT AVG(b.PAY ) FROM T_EMP2 b WHERE nvl(a.post, ' ') = nvl(b.POST, ' '))
;

SELECT AVG(b.PAY ) FROM T_EMP2 b WHERE '과장' = b.POST ;

--#7206
SELECT e.NAME "사원이름",
				(SELECT d.DNAME FROM T_DEPT2 d WHERE e.DEPTNO = d.DCODE ) "부서이름"
FROM T_EMP2 e;