--SubQuery

--#7101

SELECT * FROM T_EMP ;


--subQuery부터 만들어보고 메인쿼리를 만들자!
SELECT sal FROM T_EMP WHERE ENAME = 'SCOTT';

SELECT ENAME , SAL 
FROM T_EMP 
WHERE sal > (SELECT sal FROM T_EMP WHERE ENAME = 'SCOTT');

SELECT max(HEIGHT) FROM T_STUDENT;

SELECT NAME, HEIGHT 
FROM T_STUDENT 
WHERE HEIGHT = (SELECT max(HEIGHT) FROM T_STUDENT)
;

--1. 단일행 Sub Query
--#7103
SELECT DEPTNO1 FROM T_STUDENT WHERE NAME = '이윤나';

SELECT s.NAME "학생이름", d.DNAME "1전공"
FROM T_STUDENT s, T_DEPARTMENT d
WHERE s.DEPTNO1 = d.DEPTNO AND s.DEPTNO1 = (SELECT DEPTNO1 FROM T_STUDENT WHERE NAME = '이윤나')
;

--#7104
SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '송도권';

SELECT p.NAME , p.HIREDATE ,d.DNAME 
FROM T_PROFESSOR p, T_DEPARTMENT d
WHERE p.DEPTNO = d.DEPTNO AND p.HIREDATE > (SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '송도권');

--#7105
SELECT AVG(WEIGHT ) FROM T_STUDENT WHERE DEPTNO1 = 101;

SELECT NAME , WEIGHT 
FROM T_STUDENT 
WHERE WEIGHT > (SELECT AVG(WEIGHT ) FROM T_STUDENT WHERE DEPTNO1 = 101)
;

--#7106
SELECT NAME, HIREDATE FROM T_PROFESSOR WHERE name = '심슨';
SELECT PAY FROM T_PROFESSOR WHERE name = '조인형';

SELECT NAME , pay, HIREDATE 
FROM T_PROFESSOR 
WHERE HIREDATE = (SELECT HIREDATE FROM T_PROFESSOR WHERE name = '심슨') AND pay < ( SELECT PAY FROM T_PROFESSOR WHERE name = '조인형')
;

--#7107
SELECT *  FROM T_EMP2 ;
SELECT * FROM T_DEPT2 ;

SELECT DCODE FROM T_DEPT2 WHERE AREA = '서울지사';

SELECT EMPNO , NAME , DEPTNO 
FROM T_EMP2
WHERE DEPTNO IN (SELECT DCODE FROM T_DEPT2 WHERE AREA = '서울지사')
;

--#7108
SELECT pay FROM T_EMP2 WHERE POST = '과장';

SELECT NAME "이름", post "직급", TO_CHAR(pay, '999,999,999') || '원' "연봉"
FROM T_EMP2 
WHERE pay >=ANY (SELECT pay FROM T_EMP2 WHERE POST = '과장')
;

--#7109
SELECT WEIGHT 
FROM T_STUDENT 
WHERE GRADE = 4
;

SELECT NAME , GRADE , WEIGHT 
FROM T_STUDENT 
WHERE WEIGHT <ALL (SELECT WEIGHT FROM T_STUDENT WHERE GRADE = 4)
;